# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
#Default path for the global config file:

#    Linux: ~/.config/lazygit/config.yml
#    MacOS: ~/Library/Application\ Support/lazygit/config.yml
#    OR MacOS: export XDG_CONFIG_HOME="$HOME/.config"
#    Windows: %LOCALAPPDATA%\lazygit\config.yml (default location, but it will also be found in %APPDATA%\lazygit\config.yml

gui:
  scrollHeight: 25
  sidePanelWidth: .25
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ffcc2f"
      - "bold"
    inactiveBorderColor:
      - "#ae8c20"
    searchingActiveBorderColor:
      - "#00acee"
      - "bold"
    optionsTextColor:
      - "#00acee"
    selectedLineBgColor:
      - "#3d2a1f"
    cherryPickedCommitFgColor:
      - "#00acee"
    cherryPickedCommitBgColor:
      - "#cf5ec0"
    markedBaseCommitFgColor:
      - "#00acee"
    markedBaseCommitBgColor:
      - "#bdbe00"
    unstagedChangesColor:
      - "#ef5734"
    defaultFgColor:
      - "#ffcc2f"
os:
  editCommand: 'nvim'
  openCommand: 'kitty nvim .'
customCommands:
  # Create worktree and open new terminal there
  - key: 'W'
    context: 'localBranches'
    description: 'Create worktree from branch and open terminal there'
    prompts:
      - type: 'input'
        title: 'Worktree path:'
        key: 'Path'
        initialValue: '../{{.SelectedLocalBranch.Name}}'
    command: 'git worktree add "{{.Form.Path}}" "{{.SelectedLocalBranch.Name}}" && kitty --detach --directory "$(realpath {{.Form.Path}})"'
  # Create worktree and switch lazygit to it (replaces current session)
  - key: '<c-w>'
    context: 'localBranches'
    description: 'Create worktree and switch to it (replaces lazygit)'
    prompts:
      - type: 'input'
        title: 'Worktree path:'
        key: 'Path'
        initialValue: '../{{.SelectedLocalBranch.Name}}'
    command: 'git worktree add "{{.Form.Path}}" "{{.SelectedLocalBranch.Name}}" && cd "{{.Form.Path}}" && lazygit'
    output: terminal
